const fulltickets = "/images/fulltickets.svg";
const minasForma = "/images/minasForma.svg";
const fastfood = "/images/fastfood.png";
const rep = "/images/rep.webp";


const ProjectsData = [
    {   name:"Minas Forma, Minas Transforma",
        image: minasForma,
        link:"https://minas-forma-minas-transforma-git-demo-smarthow.vercel.app/entrar",
        description:"Web platform developed by me and used by the secretariat of culture of Minas Gerais (SECULT), for management, control and professional training of demands generated by the municipalities.",
        projectLanguage1:"Next JS",
        projectLanguage2:"Tailwind",
        projectLanguage3:"Firebase"
        
    },
    {   name:"Fulltickets",
        image: fulltickets,
        link:"https://www.fulltickets.com.br/",
        description:"Web platform for online ticket sales, application with strong UX/UI design.",
        projectLanguage1:"Next JS",
        projectLanguage2:"React JS",
        projectLanguage3:"Styled Component"
        
    },
    {
        name:"Rede Fastfood",
        image: fastfood,
        link:"https://redefastfood.com/",
        description:"Web platform in the digital menu business, with area for the delivery owner and the common user.",
        projectLanguage1:"Next JS",
        projectLanguage2:"React JS",
        projectLanguage3:"CSS"
    },
    {
        name:"Repmov Brasil",
        image: rep,
        link:"https://repmov.com/",
        description:"Application developed in flutter framework and with database in firebase. Mobile platform with multiple functionality such as airline tickets, hotels, digital banking and its main function comes with urban mobility.",
        projectLanguage1:"Flutter",
        projectLanguage2:"Firebase",
        projectLanguage3:"Dart",
    },
   

]
        
export default ProjectsData;